### ISSUE TITLE
How do anchors work

### ISSUE THREAD

**Issue by fireantik** [NeoforceControls/Neoforce-Mono#13]
Is anchor code working? Could you please provide usage sample?

**Comment by burtybob** [comment]
Hi Fireantik,

I've found that the Anchor code does work. It works the same way as it does in WinForms (if you've ever used WinForms).

Basically if you have a TabControl with a Console inside it with the Console Anchored LEFT|Right|TOP|BOTTOM then when you resize the TabControl the Console element will also expand/contract.

**Comment by jkelin** [comment]
Thank you!
