### ISSUE TITLE
Crash on Initialize

### ISSUE THREAD

**Issue by AtomicDaCat** [NeoforceControls/Neoforce-Mono#14]
An unhandled exception of type 'SharpDX.SharpDXException' occurred in SharpDX.dll

Additional information: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

**Comment by Grimston** [comment]
Do you have the same issue when using a OpenGL project?
