### ISSUE TITLE
Default.skin Non Content File

### ISSUE THREAD

**Issue by anthony-y** [NeoforceControls/Neoforce-Mono#15]
Hi,

I can't run my game because I am unable to convert the .skin file to a .xnb. Any suggestions?
"Additional information: Could not find a part of the path 'D:\Magic\C#\SolutionDir\ProjectDir\bin\Windows\Debug\Content\Skins\Default.skin'."

Thanks in advance :)

**Comment by Grimston** [comment]
Hi Anthony-y,

The .skin file is actually a zip file which contains all the .xnb files needed.

You just need to include it in your project in a Skins\ Folder in the root Content.

Hint: Set the .skin file to copy if newer
